apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dndn-api-secret
  namespace: dndn-api
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: dndn-api-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /dndn/prod/api
