apiVersion: v1
kind: Secret
metadata:
  name: dndn-api-secret
  namespace: dndn-api
type: Opaque
stringData:
  SQLALCHEMY_DATABASE_URL: "mysql+pymysql://dndn_app:q3scI.C%3EgtR8r5AUVw~VzIXlGmX4@dndn-prd-rds.cty8c6oy0gpo.ap-northeast-2.rds.amazonaws.com:3306/dndn"
  STS_EXTERNAL_ID: "DnDnExternalId"
  INTERNAL_API_KEY: "ab8i8MBKrCD0HJuFC5PBn0l4b8eHhMbo"
  GITHUB_CLIENT_ID: "Ov23lihWxHAq24hPtHCg"
  GITHUB_CLIENT_SECRET: "871aac209d413e675bdacd993f165593b7b690af"
  SLACK_CLIENT_ID: "10719586005109.10719598722773"
  SLACK_CLIENT_SECRET: "1235c534e0920e092f0a113d61f9c555"
  GITHUB_WEBHOOK_SECRET: "a5d84d0d36ff85c35f8f037466a797445e03395a2f009c3620e6dc8f5dd95e7a"
