apiVersion: v1
kind: Secret
metadata:
  name: dndn-api-secret
  namespace: dndn-api
type: Opaque
stringData:
  SQLALCHEMY_DATABASE_URL: "mysql+pymysql://dndn_app:q3scI.C%3EgtR8r5AUVw~VzIXlGmX4@dndn-prd-rds.cty8c6oy0gpo.ap-northeast-2.rds.amazonaws.com:3306/dndn"
  STS_EXTERNAL_ID: "DnDnExternalId"
  INTERNAL_API_KEY: "ab8i8MBKrCD0HJuFC5PBn0l4b8eHhMbo"
  GITHUB_CLIENT_ID: ""              # GitHub OAuth App
  GITHUB_CLIENT_SECRET: ""          # GitHub OAuth App
  SLACK_CLIENT_ID: ""               # Slack OAuth App
  SLACK_CLIENT_SECRET: ""           # Slack OAuth App
