apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dndn-web-hpa
  namespace: dndn-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dndn-web
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
