apiVersion: v1
kind: Service
metadata:
  name: dndn-web
  namespace: dndn-web
  labels:
    app: dndn-web
spec:
  type: ClusterIP
  selector:
    app: dndn-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
