apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dndn-web
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://github.com/ACS-DnDn/DnDn-Infra.git
    targetRevision: main
    path: gitops/environments/prod/apps/dndn-web
  destination:
    server: https://kubernetes.default.svc
    namespace: dndn-web
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
