apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dndn-dev-api-secret
  namespace: dndn-dev-api
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-dev
  target:
    name: dndn-dev-api-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /dndn/dev/api
