apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dndn-dev-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform-dev
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "0.20.3"
    helm:
      releaseName: external-secrets-dev
      values: |
        installCRDs: false
        serviceAccount:
          create: true
          name: external-secrets-dev
          annotations:
            eks.amazonaws.com/role-arn: REPLACE_ME_DEV_EXTERNAL_SECRETS_ROLE_ARN
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
