apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dndn-dev-web
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform-dev
  source:
    repoURL: https://github.com/ACS-DnDn/DnDn-Infra.git
    targetRevision: main
    path: gitops/environments/dev/apps/dndn-dev-web
  destination:
    server: https://kubernetes.default.svc
    namespace: dndn-dev-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
