apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../projects/platform.yaml
  - ../../../apps/dndn-web.yaml
  - ../../../apps/dndn-api.yaml
  - ../../../apps/dndn-worker.yaml
  - ../../../apps/dndn-report.yaml
  - ../../../apps/dndn-hr.yaml
