apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dndn-api
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/ACS-DnDn/DnDn-Infra.git
    targetRevision: main
    path: gitops/environments/prod/apps/dndn-api
  destination:
    server: https://kubernetes.default.svc
    namespace: dndn-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
