apiVersion: v1
kind: ConfigMap
metadata:
  name: dndn-dev-worker-config
  namespace: dndn-dev-worker
data:
  DNDN_WORKER_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/387721658341/dndn-dev-sqs-report-request"
  DNDN_WORKER_MAX_EVENTS: "500"
  DNDN_WORKER_WAIT_TIME_SECONDS: "20"
  DNDN_WORKER_MAX_MESSAGES: "1"
  AWS_REGION: "ap-northeast-2"
