apiVersion: v1
kind: ServiceAccount
metadata:
  name: dndn-dev-worker-sa
  namespace: dndn-dev-worker
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::387721658341:role/DnDn-DEV-Worker-Role
