apiVersion: v1
kind: Service
metadata:
  name: dndn-dev-worker
  namespace: dndn-dev-worker
  labels:
    app: dndn-dev-worker
spec:
  type: ClusterIP
  selector:
    app: dndn-dev-worker
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
