apiVersion: apps/v1
kind: Deployment
metadata:
  name: dndn-report-api
  namespace: dndn-report
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: dndn-report-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dndn-report-api
  template:
    metadata:
      labels:
        app: dndn-report-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: dndn-reporter-sa
      containers:
        - name: report-api
          image: 387721658341.dkr.ecr.ap-northeast-2.amazonaws.com/dndn-prd-report:d088e2aad4bd816a8aa4cb5885467c79bfc675c0
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8000
          env:
            - name: UV_NO_CACHE
              value: "true"
          envFrom:
            - configMapRef:
                name: dndn-report-config
            - secretRef:
                name: dndn-report-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dndn-report-worker
  namespace: dndn-report
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: dndn-report-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dndn-report-worker
  template:
    metadata:
      labels:
        app: dndn-report-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: dndn-reporter-sa
      containers:
        - name: report-worker
          image: 387721658341.dkr.ecr.ap-northeast-2.amazonaws.com/dndn-prd-report:d088e2aad4bd816a8aa4cb5885467c79bfc675c0
          command: ["/app/.venv/bin/python", "-m", "apps.report.src.sqs_worker"]
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: UV_NO_CACHE
              value: "true"
          envFrom:
            - configMapRef:
                name: dndn-report-config
            - secretRef:
                name: dndn-report-secret
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
