apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dndn-report-secret
  namespace: dndn-report
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: dndn-report-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /dndn/prod/report
