apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dndn-report-api-hpa
  namespace: dndn-report
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dndn-report-api
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dndn-report-worker-hpa
  namespace: dndn-report
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dndn-report-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
