apiVersion: v1
kind: Secret
metadata:
  name: dndn-report-secret
  namespace: dndn-report
type: Opaque
stringData:
  DATABASE_URL: ""                  # mysql+pymysql://USER:PASSWORD@RDS_ENDPOINT:3306/dndn
