apiVersion: v1
kind: Secret
metadata:
  name: dndn-report-secret
  namespace: dndn-report
type: Opaque
stringData:
  DATABASE_URL: "mysql+pymysql://dndn_app:q3scI.C%3EgtR8r5AUVw~VzIXlGmX4@dndn-prd-rds.cty8c6oy0gpo.ap-northeast-2.rds.amazonaws.com:3306/dndn"
