apiVersion: v1
kind: Service
metadata:
  name: dndn-report
  namespace: dndn-report
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: dndn-report-api
spec:
  type: ClusterIP
  selector:
    app: dndn-report-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
