apiVersion: apps/v1
kind: Deployment
metadata:
  name: dndn-worker
  namespace: dndn-worker
  labels:
    app: dndn-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dndn-worker
  template:
    metadata:
      labels:
        app: dndn-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: dndn-worker-sa
      containers:
        - name: worker
          image: 387721658341.dkr.ecr.ap-northeast-2.amazonaws.com/dndn-prd-worker:0fe66325aeca57071a9a4f8e3ad79f0ce90832f4
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: dndn-worker-config
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
