apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dndn-worker-hpa
  namespace: dndn-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dndn-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
